<?php

namespace Parables\Geo\Commands;

use Illuminate\Console\Command;
use Parables\Geo\Actions\DownloadAction;
use Parables\Geo\Actions\FilterFileNames;
use Parables\Geo\Actions\GetDownloadLinksAction;

class GeoCommand extends Command
{
    public $signature = 'geo:install';

    public $description = 'My command';

    const BASE_URL = "http://download.geonames.org/export/dump/";

    public function handle(): int
    {

        $this->info('This command will download a lot of files from ' . self::BASE_URL . ' . It will then perform an ExtractTransformLoad operation to populate your database. Please be patient as this will take a long time to complete');


        $countryArray = array(
            'ALL' => 'All Countires',
            'AD.zip' => 'Andorra',
            'AE.zip' => 'United Arab Emirates',
            'AF.zip' => 'Afghanistan',
            'AG.zip' => 'Antigua and Barbuda',
            'AI.zip' => 'Anguilla',
            'AL.zip' => 'Albania',
            'AM.zip' => 'Armenia',
            'AN.zip' => 'Netherlands Antilles',
            'AO.zip' => 'Angola',
            'AQ.zip' => 'Antarctica',
            'AR.zip' => 'Argentina',
            'AS.zip' => 'American Samoa',
            'AT.zip' => 'Austria',
            'AU.zip' => 'Australia',
            'AW.zip' => 'Aruba',
            'AX.zip' => 'Aland Islands',
            'AZ.zip' => 'Azerbaijan',
            'BA.zip' => 'Bosnia and Herzegovina',
            'BB.zip' => 'Barbados',
            'BD.zip' => 'Bangladesh',
            'BE.zip' => 'Belgium',
            'BF.zip' => 'Burkina Faso',
            'BG.zip' => 'Bulgaria',
            'BH.zip' => 'Bahrain',
            'BI.zip' => 'Burundi',
            'BJ.zip' => 'Benin',
            'BL.zip' => 'Saint Barthelemy',
            'BM.zip' => 'Bermuda',
            'BN.zip' => 'Brunei',
            'BO.zip' => 'Bolivia',
            'BQ.zip' => 'Bonaire, Sint Eustatius and Saba',
            'BR.zip' => 'Brazil',
            'BS.zip' => 'Bahamas',
            'BT.zip' => 'Bhutan',
            'BV.zip' => 'Bouvet Island',
            'BW.zip' => 'Botswana',
            'BY.zip' => 'Belarus',
            'BZ.zip' => 'Belize',
            'CA.zip' => 'Canada',
            'CC.zip' => 'Cocos Islands',
            'CD.zip' => 'Democratic Republic of the Congo',
            'CF.zip' => 'Central African Republic',
            'CG.zip' => 'Republic of the Congo',
            'CH.zip' => 'Switzerland',
            'CI.zip' => 'Ivory Coast',
            'CK.zip' => 'Cook Islands',
            'CL.zip' => 'Chile',
            'CM.zip' => 'Cameroon',
            'CN.zip' => 'China',
            'CO.zip' => 'Colombia',
            'CR.zip' => 'Costa Rica',
            'CS.zip' => 'Serbia and Montenegro',
            'CU.zip' => 'Cuba',
            'CV.zip' => 'Cape Verde',
            'CW.zip' => 'Curacao',
            'CX.zip' => 'Christmas Island',
            'CY.zip' => 'Cyprus',
            'CZ.zip' => 'Czech Republic',
            'DE.zip' => 'Germany',
            'DJ.zip' => 'Djibouti',
            'DK.zip' => 'Denmark',
            'DM.zip' => 'Dominica',
            'DO.zip' => 'Dominican Republic',
            'DZ.zip' => 'Algeria',
            'EC.zip' => 'Ecuador',
            'EE.zip' => 'Estonia',
            'EG.zip' => 'Egypt',
            'EH.zip' => 'Western Sahara',
            'ER.zip' => 'Eritrea',
            'ES.zip' => 'Spain',
            'ET.zip' => 'Ethiopia',
            'FI.zip' => 'Finland',
            'FJ.zip' => 'Fiji',
            'FK.zip' => 'Falkland Islands',
            'FM.zip' => 'Micronesia',
            'FO.zip' => 'Faroe Islands',
            'FR.zip' => 'France',
            'GA.zip' => 'Gabon',
            'GB.zip' => 'United Kingdom',
            'GD.zip' => 'Grenada',
            'GE.zip' => 'Georgia',
            'GF.zip' => 'French Guiana',
            'GG.zip' => 'Guernsey',
            'GH.zip' => 'Ghana',
            'GI.zip' => 'Gibraltar',
            'GL.zip' => 'Greenland',
            'GM.zip' => 'Gambia',
            'GN.zip' => 'Guinea',
            'GP.zip' => 'Guadeloupe',
            'GQ.zip' => 'Equatorial Guinea',
            'GR.zip' => 'Greece',
            'GS.zip' => 'South Georgia and the South Sandwich Islands',
            'GT.zip' => 'Guatemala',
            'GU.zip' => 'Guam',
            'GW.zip' => 'Guinea-Bissau',
            'GY.zip' => 'Guyana',
            'HK.zip' => 'Hong Kong',
            'HM.zip' => 'Heard Island and McDonald Islands',
            'HN.zip' => 'Honduras',
            'HR.zip' => 'Croatia',
            'HT.zip' => 'Haiti',
            'HU.zip' => 'Hungary',
            'ID.zip' => 'Indonesia',
            'IE.zip' => 'Ireland',
            'IL.zip' => 'Israel',
            'IM.zip' => 'Isle of Man',
            'IN.zip' => 'India',
            'IO.zip' => 'British Indian Ocean Territory',
            'IQ.zip' => 'Iraq',
            'IR.zip' => 'Iran',
            'IS.zip' => 'Iceland',
            'IT.zip' => 'Italy',
            'JE.zip' => 'Jersey',
            'JM.zip' => 'Jamaica',
            'JO.zip' => 'Jordan',
            'JP.zip' => 'Japan',
            'KE.zip' => 'Kenya',
            'KG.zip' => 'Kyrgyzstan',
            'KH.zip' => 'Cambodia',
            'KI.zip' => 'Kiribati',
            'KM.zip' => 'Comoros',
            'KN.zip' => 'Saint Kitts and Nevis',
            'KP.zip' => 'North Korea',
            'KR.zip' => 'South Korea',
            'KW.zip' => 'Kuwait',
            'KY.zip' => 'Cayman Islands',
            'KZ.zip' => 'Kazakhstan',
            'LA.zip' => 'Laos',
            'LB.zip' => 'Lebanon',
            'LC.zip' => 'Saint Lucia',
            'LI.zip' => 'Liechtenstein',
            'LK.zip' => 'Sri Lanka',
            'LR.zip' => 'Liberia',
            'LS.zip' => 'Lesotho',
            'LT.zip' => 'Lithuania',
            'LU.zip' => 'Luxembourg',
            'LV.zip' => 'Latvia',
            'LY.zip' => 'Libya',
            'MA.zip' => 'Morocco',
            'MC.zip' => 'Monaco',
            'MD.zip' => 'Moldova',
            'ME.zip' => 'Montenegro',
            'MF.zip' => 'Saint Martin',
            'MG.zip' => 'Madagascar',
            'MH.zip' => 'Marshall Islands',
            'MK.zip' => 'Macedonia',
            'ML.zip' => 'Mali',
            'MM.zip' => 'Myanmar',
            'MN.zip' => 'Mongolia',
            'MO.zip' => 'Macao',
            'MP.zip' => 'Northern Mariana Islands',
            'MQ.zip' => 'Martinique',
            'MR.zip' => 'Mauritania',
            'MS.zip' => 'Montserrat',
            'MT.zip' => 'Malta',
            'MU.zip' => 'Mauritius',
            'MV.zip' => 'Maldives',
            'MW.zip' => 'Malawi',
            'MX.zip' => 'Mexico',
            'MY.zip' => 'Malaysia',
            'MZ.zip' => 'Mozambique',
            'NA.zip' => 'Namibia',
            'NC.zip' => 'New Caledonia',
            'NE.zip' => 'Niger',
            'NF.zip' => 'Norfolk Island',
            'NG.zip' => 'Nigeria',
            'NI.zip' => 'Nicaragua',
            'NL.zip' => 'Netherlands',
            'NO.zip' => 'Norway',
            'NP.zip' => 'Nepal',
            'NR.zip' => 'Nauru',
            'NU.zip' => 'Niue',
            'NZ.zip' => 'New Zealand',
            'OM.zip' => 'Oman',
            'PA.zip' => 'Panama',
            'PE.zip' => 'Peru',
            'PF.zip' => 'French Polynesia',
            'PG.zip' => 'Papua New Guinea',
            'PH.zip' => 'Philippines',
            'PK.zip' => 'Pakistan',
            'PL.zip' => 'Poland',
            'PM.zip' => 'Saint Pierre and Miquelon',
            'PN.zip' => 'Pitcairn',
            'PR.zip' => 'Puerto Rico',
            'PS.zip' => 'Palestine',
            'PT.zip' => 'Portugal',
            'PW.zip' => 'Palau',
            'PY.zip' => 'Paraguay',
            'QA.zip' => 'Qatar',
            'RE.zip' => 'Reunion',
            'RO.zip' => 'Romania',
            'RS.zip' => 'Serbia',
            'RU.zip' => 'Russia',
            'RW.zip' => 'Rwanda',
            'SA.zip' => 'Saudi Arabia',
            'SB.zip' => 'Solomon Islands',
            'SC.zip' => 'Seychelles',
            'SD.zip' => 'Sudan',
            'SE.zip' => 'Sweden',
            'SG.zip' => 'Singapore',
            'SH.zip' => 'Saint Helena',
            'SI.zip' => 'Slovenia',
            'SJ.zip' => 'Svalbard and Jan Mayen',
            'SK.zip' => 'Slovakia',
            'SL.zip' => 'Sierra Leone',
            'SM.zip' => 'San Marino',
            'SN.zip' => 'Senegal',
            'SO.zip' => 'Somalia',
            'SR.zip' => 'Suriname',
            'SS.zip' => 'South Sudan',
            'ST.zip' => 'Sao Tome and Principe',
            'SV.zip' => 'El Salvador',
            'SX.zip' => 'Sint Maarten',
            'SY.zip' => 'Syria',
            'SZ.zip' => 'Eswatini',
            'TC.zip' => 'Turks and Caicos Islands',
            'TD.zip' => 'Chad',
            'TF.zip' => 'French Southern Territories',
            'TG.zip' => 'Togo',
            'TH.zip' => 'Thailand',
            'TJ.zip' => 'Tajikistan',
            'TK.zip' => 'Tokelau',
            'TL.zip' => 'Timor-Leste',
            'TM.zip' => 'Turkmenistan',
            'TN.zip' => 'Tunisia',
            'TO.zip' => 'Tonga',
            'TR.zip' => 'Turkey',
            'TT.zip' => 'Trinidad and Tobago',
            'TV.zip' => 'Tuvalu',
            'TW.zip' => 'Taiwan',
            'TZ.zip' => 'Tanzania',
            'UA.zip' => 'Ukraine',
            'UG.zip' => 'Uganda',
            'UM.zip' => 'United States Minor Outlying Islands',
            'US.zip' => 'United States',
            'UY.zip' => 'Uruguay',
            'UZ.zip' => 'Uzbekistan',
            'VA.zip' => 'Vatican',
            'VC.zip' => 'Saint Vincent and the Grenadines',
            'VE.zip' => 'Venezuela',
            'VG.zip' => 'British Virgin Islands',
            'VI.zip' => 'U.S. Virgin Islands',
            'VN.zip' => 'Vietnam',
            'VU.zip' => 'Vanuatu',
            'WF.zip' => 'Wallis and Futuna',
            'WS.zip' => 'Samoa',
            'XK.zip' => 'Kosovo',
            'YE.zip' => 'Yemen',
            'YT.zip' => 'Mayotte',
            'ZA.zip' => 'South Africa',
            'ZM.zip' => 'Zambia',
            'ZW.zip' => 'Zimbabwe'
        );



        // $downlaodList = (new FilterFileNames)->execute(
        // (new GetDownloadLinksAction)->execute(self::BASE_URL)
        // );

        $selectedCountries = $this->choice('Which countries would you like to populate your database with? Select as many as you want: ', $countryArray, 'ALL', multiple: true);

        $selectedCountries = array_map(fn ($fileName) => self::BASE_URL . $fileName, $selectedCountries);

        $overwrite = $this->choice('What should be done if the file has already been downloaded?', ['Skip', 'Overwrite']);

        $this->info('Your choice was: ' . $overwrite);

        $downloadAction = (new DownloadAction)->execute([$selectedCountries], $overwrite ?? false);


        // foreach ($selectedCountries as $key => $value) {

        // }

        $this->comment('All done');

        return self::SUCCESS;
    }
}
